"""add fitness_center mailing_addressn

Revision ID: 2bc67a6e6998
Revises: 88f8446617e3
Create Date: 2024-06-27 20:25:54.927113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc67a6e6998'
down_revision: Union[str, None] = '88f8446617e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_centers', sa.Column('mailing_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_centers', 'mailing_address')
    # ### end Alembic commands ###
